name: Build

on:
  repository_dispatch:
    types: [deploy]
  workflow_dispatch:

env:
  GH_REPOSITORIES: VSCodium/vscodium VSCodium/vscodium-insiders
  PACKAGE_NAME: codium
  PAGE_NAME: vscodium-repo
  PROJECT_NAME: VSCodium
  PROJECT_URL: https://github.com/VSCodium/vscodium
  R2_BUCKET_NAME: vscodium-repo
  R2_BUCKET_URL: https://r2repo.vscodium.dev
  REPO_ARCH_DEB: amd64 arm64 armhf
  REPO_ARCH_RPM: x86_64 aarch64 armv7hl
  REPO_NAME: vscodium
  REPO_URL: https://repo.vscodium.dev

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          until sudo apt update
          do
            sleep 1
          done
          sudo apt install -y jq createrepo-c coreutils gnupg2 dpkg-dev reprepro

      - name: Setup Node.js environment
        uses: actions/setup-node@v4
        with:
          node-version: '20.18.3'

      - name: Configure GPG
        run: |
          echo GNUPGHOME="$(mktemp -d /tmp/pgpkeys-XXXXXX)" >> $GITHUB_ENV

      - name: Import GPG key
        id: import_gpg
        uses: crazy-max/ghaction-import-gpg@v6
        with:
          gpg_private_key: ${{ secrets.GPG_PRIVATE_KEY }}
          passphrase: ${{ secrets.GPG_PASSPHRASE }}
          trust_level: 5

      - name: Confirm GPG key
        run: |
          gpg --list-keys
          echo "${{ steps.import_gpg.outputs.fingerprint }}"

      - name: Build pages
        env:
          GPG_FINGERPRINT: ${{ steps.import_gpg.outputs.fingerprint }}
        run: ./scripts/build_pages.sh

      - name: Build repositories
        env:
          GPG_FINGERPRINT: ${{ steps.import_gpg.outputs.fingerprint }}
        run: ./scripts/build_repos.sh

      - name: Upload packages
        env:
          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          CLOUDFLARE_KV_NAMESPACE_ID: ${{ secrets.CLOUDFLARE_KV_NAMESPACE_ID }}
        run: ./scripts/upload_r2.sh

      - name: Move repositories
        run: |
          mv pkgs/* _site

      - name: Compress site.tar.gz
        run: |
          tar -czf site.tar.gz _site

      - name: Upload site.tar.gz
        uses: actions/upload-artifact@v4
        with:
          name: site
          path: ./site.tar.gz
          retention-days: 1

      - name: Deploy site
        env:
          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
        run: ./scripts/deploy.sh

      - name: Clean packages
        env:
          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          CLOUDFLARE_KV_NAMESPACE_ID: ${{ secrets.CLOUDFLARE_KV_NAMESPACE_ID }}
        run: ./scripts/clean_r2.sh
