name: "CI - Main: Build & Lint"

on:
  push:
    branches:
      - main
    paths-ignore:
      - "**/*.md"

env:
  GH_REPOSITORIES: VSCodium/vscodium VSCodium/vscodium-insiders
  PACKAGE_NAME: codium
  PAGE_NAME: vscodium-repo
  PROJECT_NAME: VSCodium
  PROJECT_URL: https://github.com/VSCodium/vscodium
  R2_BUCKET_NAME: vscodium-repo
  R2_BUCKET_URL: https://r2repo.vscodium.dev
  REPO_ARCH_DEB: amd64 arm64 armhf
  REPO_ARCH_RPM: x86_64 aarch64 armv7hl
  REPO_NAME: vscodium
  REPO_URL: https://repo.vscodium.dev

permissions: {}

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          fetch-depth: 0
          persist-credentials: false

      - name: Install dependencies
        run: |
          until sudo apt update
          do
            sleep 1
          done
          sudo apt install -y jq createrepo-c coreutils dpkg-dev reprepro

      - name: Install zizmor
        run: |
          pipx install zizmor

      - name: Setup Node.js environment
        uses: actions/setup-node@48b55a011bda9f5d6aeb4c2d9c7362e8dae4041e # v6.4.0
        with:
          node-version-file: .nvmrc
          package-manager-cache: false

      - name: Setup
        run: ./scripts/setup.sh

      - name: Build repositories
        run: ./scripts/build_repos.sh

      - name: Build pages
        run: ./scripts/build_pages.sh

      - name: Lint code
        run: |
          npm run lint:all

      - name: Lint commit
        run: |
          if [[ "${BASE_SHA}" = "0000000000000000000000000000000000000000" ]]; then
            npx commitlint --to HEAD --verbose
          else
            npx commitlint --from "${BASE_SHA}" --to "${HEAD_SHA}" --verbose
          fi
        env:
          BASE_SHA: ${{ github.event.before }}
          HEAD_SHA: ${{ github.event.head_commit.id }}
